name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build Code
        run: npm run build:noemit

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Check Formatting
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Lint Code
        run: npm run lint

  publish:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [build, format, lint]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-cache-

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build
        run: npm run build:only

      - name: Publish
        run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Pack
        run: npm pack --verbose

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.tgz,LICENSE,README.md'
          token: ${{ secrets.GITHUB_TOKEN }}
